version: '3'
services:
    frontend:
      build:
        context: './docker-react'
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      container_name: react-container
      environment:
        - WATCHPACK_POLLING=true
      networks:
        - mern-stack-network
      volumes:
        - ./docker-react:/app
      depends_on:
        - backend
    backend:
      build:
        context: './express-docker'
        dockerfile: Dockerfile
      ports:
        - 5500:5500
      container_name: express-container
      networks:
        - mern-stack-network
      volumes:
        - ./express-docker:/app
      depends_on:
        - mongodb
    mongodb:
      image: mongo
      ports:
        - 27017:27017
      container_name: mongo-container
      networks:
        - mern-stack-network
      volumes:
        - mongoData:/data/db
      env_file:
        - .env
networks:
  mern-stack-network:
volumes:
  mongoData:
    